name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build

      - name: Read json data from json file
        uses: loveloper44/render-json-action@v2.0.2
        id: render
        with:
          json: ./public/gatsby-posts.json

      - name: Get the output
        run: echo "${{ steps.render.outputs.result }}"

      - name: log the WEBHOOK_URL
        run: echo ${{ secrets.WEBHOOK_URL }}

      - name: Send data to webhook url
        uses: jasongitmail/fast-webhook@v1
        with:
        url: ${{ secrets.WEBHOOK_URL }}
        json: '{"foo": "bar"}'

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.

